In [1]:
import numpy as np
from sklearn.decomposition import NMF

In [2]:
X = np.array([[1,1,5,2,3], [0,6,2,1,1], [3, 4,0,3,1], [4, 1,5,6,3]])
model = NMF(n_components=2)

In [3]:
print(X)

[[1 1 5 2 3]
 [0 6 2 1 1]
 [3 4 0 3 1]
 [4 1 5 6 3]]


In [4]:
W = model.fit_transform(X)
H = model.components_
print(W)

[[1.6282913  0.026322  ]
 [0.39902207 2.18571672]
 [0.75831737 1.53056852]
 [2.59747358 0.01899844]]


In [5]:
print(H)

[[1.35733834 0.41051184 2.16402106 2.04702128 1.33550911]
 [0.25412802 2.58522943 0.         0.3642873  0.14243281]]


In [12]:
#importer les données
import pandas as pd
train_data = pd.read_csv(r"income/train-data.csv")
test_data = pd.read_csv(r"income/test-data.csv")

print(train_data.shape)

(100, 5)


In [25]:
model1 = NMF(n_components=4)

In [26]:
W = model1.fit_transform(train_data)
H = model1.components_

print(W.shape)
print(W)

(100, 4)
[[1.37660820e+00 3.03889621e+00 1.13039820e+00 3.39514707e-01]
 [4.49671344e+00 2.35981154e+00 2.34332050e-01 0.00000000e+00]
 [2.90848545e+00 0.00000000e+00 2.14419156e+00 4.74008634e+00]
 [3.89453649e+00 1.76690853e+00 1.74935249e-02 1.62711532e+00]
 [1.68520916e+00 2.51875653e+00 6.55263530e-01 5.43841021e-02]
 [3.14338170e+00 3.96302244e-01 2.21283029e-01 0.00000000e+00]
 [2.61947949e+00 1.39861163e+00 5.11449886e-01 0.00000000e+00]
 [4.01511474e+00 2.80259676e+00 3.49502451e-01 1.42925145e-01]
 [4.47920674e+00 1.57801204e+00 3.43047929e-02 5.46401814e-02]
 [1.64569128e+00 1.10496038e+00 2.24483587e+00 1.80881038e-01]
 [3.05152409e+00 2.45542526e+00 9.59127748e-01 1.52878944e-01]
 [3.05169654e+00 2.45535316e+00 1.02143571e+00 1.52327598e-01]
 [2.35752577e+00 1.11079474e+00 2.00901768e+00 0.00000000e+00]
 [3.44896058e+00 3.21094355e-01 2.03094373e+00 0.00000000e+00]
 [3.62530579e+00 1.92589110e+00 6.05035648e-02 6.84889728e-01]
 [3.31796559e+00 2.93852619e+00 4.47509785e-01

In [27]:
print(H)

[[6.71641029e+00 2.29049565e+01 8.25962669e+00 1.18377186e-01
  4.69836325e-02]
 [8.64738515e-01 2.20046826e-04 2.02801615e+01 5.86239466e-02
  9.36018717e-02]
 [1.60310640e+01 0.00000000e+00 0.00000000e+00 1.12885453e-01
  6.75268705e-02]
 [1.94179336e-02 7.25137540e+00 0.00000000e+00 0.00000000e+00
  8.36539982e-02]]
