### basic tests on normalisation and label encoding, useful to prepare dataset with non numerical variables

In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [3]:
# SCALING ET NORMALISATION
X_train = np.array([[1,-1,2], [2,0,0], [0,1,-1]])
X_train

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1, -1]])

In [4]:
X_train.mean(axis=0)

array([1.        , 0.        , 0.33333333])

In [5]:
X_train.var(axis=0)

array([0.66666667, 0.66666667, 1.55555556])

In [8]:
# better to use a scaler object, can be useful for reversing normalisation
#X_scaled = preprocessing.scale(X_train)

myscaler = preprocessing.StandardScaler().fit(X_train)

X_scaled = myscaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
X_unscaled = myscaler.inverse_transform(X_scaled)
X_unscaled

array([[ 1.00000000e+00, -1.00000000e+00,  2.00000000e+00],
       [ 2.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00, -1.00000000e+00]])

In [82]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [83]:
X_scaled.var(axis=0)

array([1., 1., 1.])

In [84]:
#Manual normalising
X_ManNormal = (X_train - X_train.mean(axis=0))/X_train.var(axis=0)
X_ManNormal

array([[ 0.        , -1.5       ,  1.07142857],
       [ 1.5       ,  0.        , -0.21428571],
       [-1.5       ,  1.5       , -0.85714286]])

In [85]:
X_normalized = preprocessing.normalize(X_train)#, norm ='l2')
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [86]:
np.linalg.norm(X_normalized,axis=1)

array([1., 1., 1.])

In [1]:
# LABEL ENCODER
from sklearn.preprocessing import LabelEncoder
navigateur = ('firefox','chrome','safari','internet_explorer')

navig_df = pd.DataFrame(navigateur, columns=['nom_navigateur'])

labelencoder = LabelEncoder()

navig_df['nom_navig_cat']= labelencoder.fit_transform(navig_df['nom_navigateur'])
navigdf

NameError: name 'pd' is not defined

In [95]:
# ONE HOT ENCODER
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')

enc_df = pd.DataFrame(enc.fit_transform(navig_df[['nom_navig_cat']]).toarray())

navig_df = navig_df.join(enc_df)

In [96]:
navig_df

nom_navigateur  nom_navig_cat    0    1    2    3
0            firefox              1  0.0  1.0  0.0  0.0
1             chrome              0  1.0  0.0  0.0  0.0
2             safari              3  0.0  0.0  0.0  1.0
3  internet_explorer              2  0.0  0.0  1.0  0.0