In [2]:
import numpy as np


In [3]:
# Tableau d'entiers:
np.array([1, 4, 2, 5, 3])

# Une liste de listes est transformée en un tableau multi-dimensionnel
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)

# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)

# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

# Celle-ci vous la conaissez déjà! Essayez aussi "randint" et "normal"
np.random.random((3, 3))

# La matrice identité de taille 3x3 
# (matrice identité : https://fr.wikipedia.org/wiki/Matrice_identit%C3%A9)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print(x1)
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

[5 0 3 3 7 9]
nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


In [14]:
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

# On peut aussi modifier les valeur
x1[1] = "1000"
print(x1)

# Attention au type (ici la valeur 3.14 est tronquée en rentrant dans le tableau)
x1[1] = 3.14
print(x1)

[5 0 3 3 7 9]
5
9
5
[   5 1000    3    3    7    9]
[5 3 3 3 7 9]


In [15]:
# x[début:fin:pas]
print(x1[:2])  # Les cinq premiers éléments
print(x1[2:])  # Les éléments à partir de l'index 5
print(x1[::2])  # Un élément sur deux

[5 3]
[3 3 7 9]
[5 3 7]


In [17]:
x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2)
print(x2[0,1])
x2[0,:] #premiere ligne

[[2 3 8 1]
 [3 3 3 7]
 [0 1 9 9]]
3


array([2, 3, 8, 1])

In [18]:
#concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [19]:
#concatenation verticale : vStack ou horizontale hstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [20]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [21]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [24]:
#operation booleene
x = np.random.rand(3,3)
print(x)
x > 0.5

[[0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672]]


array([[ True,  True,  True],
       [ True, False, False],
       [ True, False,  True]])

In [25]:
#renvoit index des endroit ou condition verifiée :
# liste1 index ligne
# liste2 index colonne
np.where(x > 0.5)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 0, 2], dtype=int64))

In [26]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.67063787 0.21038256 0.1289263  0.31542835]
 [0.36371077 0.57019677 0.43860151 0.98837384]
 [0.10204481 0.20887676 0.16130952 0.65310833]]
La somme de tous les éléments de M:  4.811597382346344
Les sommes des colonnes de M:  [1.13639345 0.98945609 0.72883733 1.95691051]


In [27]:
a = np.arange(3)
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])